baseurl = "https://takuto-n.github.io/takuto-n.github.io/"
title = "Little by little and bit by bit"
author = "takuto-nrkn"
canonifyurls = true
paginate = 3
theme = "hyde"
publishDir = "docs"
hasCJKLanguage = true
languageCode = "ja-jp"